function(build MODULE_NAME MODULE_PATH)
    option(ZLIB_BUILD_TESTING "Enable Zlib Examples as tests" OFF)
    option(ZLIB_BUILD_SHARED "Enable building zlib shared library" OFF)
    option(ZLIB_BUILD_STATIC "Enable building zlib static library" ON)
    option(ZLIB_BUILD_MINIZIP "Enable building libminizip contrib library" OFF)
    option(ZLIB_INSTALL "Enable installation of zlib" OFF)
    option(ZLIB_PREFIX "prefix for all types and library functions, see zconf.h.in" OFF)
    set( ZLIB_BUILD 1 )
    add_subdirectory( ${MODULE_PATH} )
endfunction(build MODULE_NAME MODULE_PATH)
